### ISSUE TITLE
readme issues

### ISSUE THREAD

**Issue by rhagarty** [IBM/Train-Custom-Speech-Model#20]
Step 1. Create Watson Service

- the description doesn't match the contents of the latest `services.sample.json` file. USERNAME and PASSWORD are not found in the file. 

Step 2. Set up your code

- the newly created file "services.json" needs to be in root, not 'client'.
- need to do `'npm istall` at root level also.
- I did not need to launch browser, it came up automatically

**Comment by tonanhngo** [comment]
Thanks Rich, we just updated the credential mechanism to use the newer apikey approach instead of the older username/password.  I will update the instruction in the README along with the npm command.
