### ISSUE TITLE
converting rtf files to txt

### ISSUE THREAD

**Issue by rhagarty** [IBM/Train-Custom-Speech-Model#21]
`python convert_rtf.py *.rtf` does not work. It only works on one file at a time (wildcards not allowed)

**Comment by rhagarty** [comment]
This script worked for me:

```python
import os
source = '.'

files = os.listdir(source)

for f in files:
    if f.endswith("rtf"):
        print 'Converting ' + f
        os.system("python convert_rtf.py " + f)
```

**Comment by tonanhngo** [comment]
Ah you are right, I actually used a for loop in bash, and documented it incorrectly in the README.  Let me fix it.
