### ISSUE TITLE
create language model fails

### ISSUE THREAD

**Issue by rhagarty** [IBM/Train-Custom-Speech-Model#23]
`cmd/create_language_model.py` fails with following message:

`Please set your username in the environment variable USERNAME`

This is due to the `apikey` issue which needs to be consistently used. `services.json` doesn't use USERNAME and PASSWORD, so all of the python scripts need to be modified to accept `apikey`.

**Comment by tonanhngo** [comment]
Hi Rich, the python scripts are set up to accept both types of credential for flexibility.  If you have the api key, then you can set the environment variable as:
export USERNAME=apikey
export PASSWORD=<your-IAM-apikey>
This is explained in the instruction, but I guess it would be helpful to say this in the error message also, so let me do that.
