### ISSUE TITLE
error: 'Not authorized to view this resource'

### ISSUE THREAD

**Issue by itzzi** [IBM/Train-Custom-Speech-Model#58]
I tried to deploy the app locally and at IBM Cloud - I'm getting this error:

<img width="1429" alt="Screen Shot 2019-03-27 at 13 26 19" src="https://user-images.githubusercontent.com/10403554/55091110-822d8c00-50b0-11e9-9766-7f8a9452b25c.png">

I guess it's related to auth, but not sure how to fix it.

Thanks!

**Comment by rhagarty** [comment]
@itzzi - the app should come up on on it's own on port 3000. Why is the link you show using port 5000?

**Comment by itzzi** [comment]
@rhagarty it's the port defined by default here: https://github.com/IBM/Train-Custom-Speech-Model/blob/master/server/server.ts

**Comment by itzzi** [comment]
@rhagarty my fault - I managed to deploy the app! Thanks!

A couple of suggestions:
- it would be great if language and narrow/broad band could be selected by user
- same for all custom models (acoustic and language)

Thanks again
