### ISSUE TITLE
There seems to be missing steps for deploying this to IBM Cloud.

### ISSUE THREAD

**Issue by Twanawebtech** [IBM/Train-Custom-Speech-Model#62]
There seem to be missing steps for deploying this to IBM Cloud using Cloud Foundry. 
Are you guys planning to add that soon? 

Thanks.

**Comment by pvaneck** [comment]
I think it would be worthwhile to have some instructions for deploying the app to IBM Cloud. I will look into this.

**Comment by Twanawebtech** [comment]
@pvaneck the link is broken 
![image](https://user-images.githubusercontent.com/12715466/56652571-977fe100-6683-11e9-8ddb-8c2dba0cc711.png)

And deploying this to CF would not just work, you need to make the necessary changes in the application when doing CF Push. Also, I see the .cfignore is missing, something we should have when deploying to IBM Cloud. 


Please reopen this issue and close the issue when instructions added.

**Comment by pvaneck** [comment]
@Twanawebtech Good catch. A fix was just pushed. As for testing deploying, I did manage to get the app up and running on IBM Cloud here: https://stt-customizer.mybluemix.net (Will probably take this down sometime soon though)
