### ISSUE TITLE
Error while uploading text corpus and audio zip files

### ISSUE THREAD

**Issue by rohitk9** [IBM/Train-Custom-Speech-Model#82]
![Screenshot 2020-01-28 at 12 40 04 PM](https://user-images.githubusercontent.com/59723722/73242593-74aeca00-41cb-11ea-9d86-cb167fff1b36.png)

I have installed all the dependencies and prepared the data as asked in the instructions. Where am I going wrong here ?

**Comment by pvaneck** [comment]
Do the node server logs say anything? These should just be in the console where you started the server (by probably running the `npm run dev` command).

**Comment by rohitk9** [comment]
![Screenshot 2020-01-29 at 11 04 22 AM](https://user-images.githubusercontent.com/59723722/73330605-4098df00-4287-11ea-9d83-9d10a132af21.png)

These are the few server logs which I think might have added to this issue : 

1) node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v79-darwin-x64.tar.gz 
2) node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@13.7.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp) 
3) found 71 vulnerabilities (63 low, 2 moderate, 6 high)
  run `npm audit fix` to fix them, or `npm audit` for details

After running 'npm audit fix', it displays a message 'Compiled successfully' and the local host is launched in the browser.

But my initial issue regarding the uploading of files still persists. Kindly guide me where am I going wrong.

**Comment by rohitk9** [comment]
![Screenshot 2020-01-29 at 12 29 38 PM](https://user-images.githubusercontent.com/59723722/73334580-249b3a80-4293-11ea-8ba1-437cbbd14b83.png)

These are the logs that are coming up after I login and click on the Corpora option in the UI.

**Comment by pvaneck** [comment]
Looks like your Watson Speech to Text service right now is the free (Lite) plan. Unfortunately, customization capabilities are not included in this plan, and the Standard plan is needed for which you'll need an upgraded account. More info can be found [here](https://cloud.ibm.com/docs/account?topic=account-accounts#upgrade-lite-account). Promotional credit that is given when you upgrade can be used towards the standard plan if you still want to try this out.

**Comment by rohitk9** [comment]
Okay, thank you for clearing that out.
