### ISSUE TITLE
EZdi dataset

### ISSUE THREAD

**Issue by gguerrab** [IBM/Train-Custom-Speech-Model#94]
Trying to create a custom STT for medical dictation. I was trying to get the dataset from EZdi but is no longer available. 
https://www.ezdi.com/open-datasets/

Can anyone provide a copy of it or recommend another source?

**Comment by rhagarty** [comment]
@pvaneck - are you aware of this issue with the data? You can request a download, but doesn't appear to do anything.

**Comment by pvaneck** [comment]
Hmm, I was not aware. Looks like some issues with the js after form submission. I can try and reach out to some ezDI folks about this.

**Comment by gguerrab** [comment]
I would really appreciate it. I actually talked to the CEO. He was really nice and connected me to someone in the company who was supposed to help, but I haven’t heard back. 
Maybe you have better connections and luck.

**Comment by pvaneck** [comment]
I sent out an email to them last week, and from checking just now, the downloads seem to be working again. So whatever issue was causing the downloads not to work seems to be resolved.

**Comment by afeltham** [comment]
Can i check i have the correct link for this? The page shown above doesn't seem to have any mention of downloads, but the most recent comment suggests that it is all working. Perhaps i've missed something. Thanks.

**Comment by fi-da** [comment]
From WayBack Machine:
https://d376himta3otg7.cloudfront.net/opendataset/Documents.zip
https://d376himta3otg7.cloudfront.net/opendataset/Audio.zip

**Comment by afeltham** [comment]
Thank you very much @fi-da :)

**Comment by prsnt558908** [comment]
@fi-da above links are not working, it would be really great if you can please share again.

**Comment by firefox1221** [comment]
The files are missing ... please someone re-upload them to google drive or somewhere else ... can't seem to find them anywhere!

**Comment by firefox1221** [comment]
Btw ... if I have my own audio file ... can I use a random text file to represent the transcription .... I'm just trying to go around the problem ... did anyone test this?

**Comment by pvaneck** [comment]
Sorry everyone. Just updated the link.
